---
## Checkout docker-znc and run znc in a docker container
-
  hosts: znc
  tasks:
  - name:  checkout repo from github
    git:   repo={{ docker_znc_repo }}
           dest=/tmp/docker-images/docker-znc

  - name:  build docker image
    shell: cd /tmp/docker-images/docker-znc ; docker build -t docker-znc .

  - name:  run docker container
    shell: docker run -d -u irc -p 3030:6667 docker-znc zncrun {{ znc_user }} {{ znc_password}}
    ignore_errors: True


