---
- name: ensure the build dir exists
  file: path="{{ build_dir }}" state=directory

- name: checkout repo from github
  git: repo="{{ docker_znc_repo }}" dest="{{ build_dir }}"

- name:  build docker image
  shell: docker build -t {{ image_tag }} . chdir={{ build_dir}}

- name:  run docker container
  docker: > 
    image="{{ image_tag }}"
    port=3030:6667
    command=zncrun {{ znc_user}} {{ znc_password }}
    name="{{ container_name }}"


